on:
  pull_request: {}
name: Semgrep Staging
jobs:
  semgrep-staging:
    name: Scan
    runs-on: ubuntu-latest
    env:	
      INPUT_PUBLISHURL: https://staging.semgrep.dev
      GITHUB_ACTIONS: 1
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      with:
        publishToken: ${{ secrets.SEMGREP_STAGING_SECRET }}
        publishDeployment: 53
