name: Semgrep CI

on:
  workflow_call:
    inputs:
      docker_tag:
        required: true
        type: string
    inputs:
      app_url:
        required: true
        type: string
    secrets:
      app_token:
        required: true

jobs:
  semgrep-ci:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep:${{ inputs.docker_tag }}
    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci
        env:
          SEMGREP_APP_URL: ${{ inputs.app_url }}
          SEMGREP_APP_TOKEN: ${{ secrets.app_token }}
