on:
  pull_request: {}
name: Semgrep
jobs:
  semgrep-prod:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      env:
        SEMGREP_AGENT_DEBUG: 1
      with:
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
        publishDeployment: 138 # organization: semgrep
